apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: dev
  labels:
    k8s-app: nginx-test
  annotations:
    d-engine.ip6n.net/gitRepo: "https://github.com/ip6n/nginx-test.git"
    d-engine.ip6n.net/backupBlock: "{{ blockId }}"
    d-engine.ip6n.net/ipv4: "auto"
    d-engine.ip6n.net/vs-http-desc: "HTTP traffic to nginx-test"
    d-engine.ip6n.net/vs-http-vsPort: "80"
    d-engine.ip6n.net/vs-http-template: "vs-tcp"
    d-engine.ip6n.net/vs-http-fwPermit: "0.0.0.0/0"
spec:
  selector:
    k8s-app: nginx-test
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
