apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-test
  namespace: dev
  labels:
    k8s-app: nginx-test
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: nginx-test
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: nginx-test
        version: v1
    spec:
      containers:
      - name: nginx-test
        image: nginx:1.8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
